# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: name_node.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'name_node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fname_node.proto\x12\x08nameNode\"<\n\x0fRegisterRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\x0f\n\x07storage\x18\x03 \x01(\x05\"\x1e\n\x10RegisterResponse\x12\n\n\x02id\x18\x01 \x01(\t\" \n\x10\x44\x61taNodesRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\":\n\x11\x44\x61taNodesResponse\x12%\n\x05nodes\x18\x01 \x03(\x0b\x32\x16.nameNode.DataNodeInfo\"E\n\x0c\x44\x61taNodeInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\x12\x0f\n\x07storage\x18\x04 \x01(\x05\"4\n\x0e\x41\x64\x64UserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"!\n\x0f\x41\x64\x64UserResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"9\n\x13ValidateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"&\n\x14ValidateUserResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xac\x02\n\x0fnameNodeService\x12\x41\n\x08Register\x12\x19.nameNode.RegisterRequest\x1a\x1a.nameNode.RegisterResponse\x12G\n\x0cGetDataNodes\x12\x1a.nameNode.DataNodesRequest\x1a\x1b.nameNode.DataNodesResponse\x12>\n\x07\x41\x64\x64User\x12\x18.nameNode.AddUserRequest\x1a\x19.nameNode.AddUserResponse\x12M\n\x0cValidateUser\x12\x1d.nameNode.ValidateUserRequest\x1a\x1e.nameNode.ValidateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'name_node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=29
  _globals['_REGISTERREQUEST']._serialized_end=89
  _globals['_REGISTERRESPONSE']._serialized_start=91
  _globals['_REGISTERRESPONSE']._serialized_end=121
  _globals['_DATANODESREQUEST']._serialized_start=123
  _globals['_DATANODESREQUEST']._serialized_end=155
  _globals['_DATANODESRESPONSE']._serialized_start=157
  _globals['_DATANODESRESPONSE']._serialized_end=215
  _globals['_DATANODEINFO']._serialized_start=217
  _globals['_DATANODEINFO']._serialized_end=286
  _globals['_ADDUSERREQUEST']._serialized_start=288
  _globals['_ADDUSERREQUEST']._serialized_end=340
  _globals['_ADDUSERRESPONSE']._serialized_start=342
  _globals['_ADDUSERRESPONSE']._serialized_end=375
  _globals['_VALIDATEUSERREQUEST']._serialized_start=377
  _globals['_VALIDATEUSERREQUEST']._serialized_end=434
  _globals['_VALIDATEUSERRESPONSE']._serialized_start=436
  _globals['_VALIDATEUSERRESPONSE']._serialized_end=474
  _globals['_NAMENODESERVICE']._serialized_start=477
  _globals['_NAMENODESERVICE']._serialized_end=777
# @@protoc_insertion_point(module_scope)
