# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_node.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'data_node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61ta_node.proto\x12\tdata_node\"o\n\tFileChunk\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x14\n\x0c\x63hunk_number\x18\x03 \x01(\x05\x12\x14\n\x0ctotal_chunks\x18\x04 \x01(\x05\x12\x10\n\x08username\x18\x05 \x01(\t\"\x17\n\x05Reply\x12\x0e\n\x06length\x18\x01 \x01(\x05\"\"\n\x0eGetFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t2|\n\x08\x44\x61taNode\x12\x32\n\x08SendFile\x12\x14.data_node.FileChunk\x1a\x10.data_node.Reply\x12<\n\x07GetFile\x12\x19.data_node.GetFileRequest\x1a\x14.data_node.FileChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOCKCHUNK']._serialized_start=30
  _globals['_BLOCKCHUNK']._serialized_end=142
  _globals['_REPLY']._serialized_start=144
  _globals['_REPLY']._serialized_end=167
  _globals['_GETFILEREQUEST']._serialized_start=169
  _globals['_GETFILEREQUEST']._serialized_end=203
  _globals['_HEARTBEATREQUEST']._serialized_start=204
  _globals['_HEARTBEATREQUEST']._serialized_end=222
  _globals['_HEARTBEATRESPONSE']._serialized_start=224
  _globals['_HEARTBEATRESPONSE']._serialized_end=259
  _globals['_DATANODE']._serialized_start=262
  _globals['_DATANODE']._serialized_end=458
# @@protoc_insertion_point(module_scope)
