name: Backend Linter

on:
  push:
    branches: ["test"]
  pull_request:
    branches: ["test"]

jobs:
  linter:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run autopep8 on all Python files
        run: |
          cd backend
          find . -name "*.py" -not -path "./venv/*" -not -path "./__pycache__/*" | xargs autopep8 --in-place --aggressive --aggressive

      - name: Run Flake8
        run: |
          cd backend
          flake8 . --config=.flake8